### ISSUE TITLE
Server 500 error: Failed to lookup view "index" in views directory 

### ISSUE THREAD

**Issue by jahde** [Torone/GhosToro#2]
Hi I am trying to install the Ghostoro theme and have followed the directions exactly. It works locally but when i try to push up to heroku I am getting this error message:

Server 500 error: Failed to lookup view "index" in views directory 

I have a index.hbs in my root directory for Ghostoro and I've tested other themes which work on heroku production. Any help would be greatly appreciated!

 ERROR: Failed to lookup view "index" in views directory "/app/content/themes/GhosToro-master" 
2015-05-24T20:11:03.960166+00:00 app[web.1]:  Rendering Error Page 
2015-05-24T20:11:03.960168+00:00 app[web.1]:  Ghost caught a processing error in the middleware layer. 
2015-05-24T20:11:03.960170+00:00 app[web.1]:  Error: Failed to lookup view "index" in views directory "/app/content/themes/GhosToro-master"
2015-05-24T20:11:03.960178+00:00 app[web.1]:     at Promise._settlePromiseAt (/app/node_modules/bluebird/js/main/promise.js:530:18)
2015-05-24T20:11:03.960176+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:24:31)
2015-05-24T20:11:03.960171+00:00 app[web.1]:     at EventEmitter.app.render (/app/node_modules/express/lib/application.js:555:17)
2015-05-24T20:11:03.960172+00:00 app[web.1]:     at ServerResponse.res.render (/app/node_modules/express/lib/response.js:938:7)
2015-05-24T20:11:03.960174+00:00 app[web.1]:     at /app/core/server/controllers/frontend.js:223:25
2015-05-24T20:11:03.960177+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/main/promise.js:454:31)
2015-05-24T20:11:03.960181+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/main/async.js:177:16)
2015-05-24T20:11:03.960180+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/main/promise.js:646:14)
2015-05-24T20:11:03.960195+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/main/async.js:187:10)
2015-05-24T20:11:03.960200+00:00 app[web.1]: 
2015-05-24T20:11:03.960199+00:00 app[web.1]:     at processImmediate [as _immediateCallback](timers.js:321:17) 
2015-05-24T20:11:03.960197+00:00 app[web.1]:     at Immediate.Async.drainQueues [as _onImmediate](/app/node_modules/bluebird/js/main/async.js:15:14)
2015-05-24T20:11:04.137746+00:00 app[web.1]: 207.237.79.89 - - [24/May/2015:20:11:04 +0000] "GET /ghost/ghost.min.css?v=bd14e1d4db HTTP/1.1" 304 - " "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36"
2015-05-24T20:11:03.973124+00:00 app[web.1]: 207.237.79.89 - - [24/May/2015:20

**Comment by gauravChaturvedi** [comment]
Any luck ?

**Comment by gauravChaturvedi** [comment]
I'm facing the same issue.

**Comment by wetzel** [comment]
500
[post.hbs] Parse error on line 50: ...{/post}} {{< comments-disqus}} ---------------------^ Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'

**Comment by Torone** [comment]
Probably you're not pushing the views to the server.
Try to remove these two lines from the .github file:

```
/*.hbs
/partials/*.hbs
```

Let me know.

**Comment by atlanical** [comment]
Doesn't work on an apache server without using git, I just get a 

500
[index.hbs] The partial menu could not be found
Go to the front page →

**Comment by Torone** [comment]
It is a server side error, It looks like there is not view in there... you should double check it.
I have several people with this theme installed and the only issue they had it was on Heroku because the .gitignore was not uploading the view files.
I don't know how to help.

**Comment by atlanical** [comment]
Not sure mate, I've got everything in the theme folder which is here: https://github.com/Torone/GhosToro/tree/master/dev also I've tried removing the two lines from the gitignore but I don't think that will be effected by it since that's for if you are using git commands?

**Comment by Torone** [comment]
But did you compiled it? You should not upload the dev folder in your server. 
Once compiled you will get the files outside the dev folder with all the js and css minified and all you need to do is to upload all those files except the dev folder as explained in the tutorial.

**Comment by atlanical** [comment]
Ah that's why :+1: I don't think I can do that without installing grunt which I don't think will work nicely on my interworx installation. Thanks :)

**Comment by Torone** [comment]
You can easily do it on your local machine before uploading the file on your server.

**Comment by roadev** [comment]
I run this commands into dev folder:
<code>npm install</code> to load Grunt dependencies
<code>grunt</code> to create the necessary production files

**Comment by Torone** [comment]
it should have created few files in your root directory. Just upload everything now except the dev folder and you should be ok.

**Comment by wetzel** [comment]
Thanks for the hint. However, did not solve the problem. Still get an error
message:

500
[post.hbs] Parse error on line 50: ...{/post}} {{< comments-disqus}}
---------------------^ Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN',
'UNDEFINED', 'NULL', 'DATA', got 'INVALID'

**Comment by Torone** [comment]
ok, this is because if you wish to use Disqus you need to register to it and update the `comments-disqus` partial view with your ID. Otherwise just comment it out in this way: `{{! < comments-disqus }}`.

**Comment by roadev** [comment]
@Torone Where do I place my Disqus ID?

**Comment by Torone** [comment]
within the `comments-disqus.hbs` there is a line:
`var disqus_shortname = 'DISQUS_ID';`

**Comment by Torone** [comment]
I think all the issues has been solved here. Enjoy!
